# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  # Configure provisioning
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "start.sh", run: "always"
  # Configure network ports
  config.vm.network "forwarded_port", host: 8888, host_ip: "192.168.33.15", guest: 8888 # Jupyter notebook
  config.vm.network "forwarded_port", host: 4043, guest: 4043 # Spark job
  config.vm.network "forwarded_port", host: 4041, guest: 4041 # Spark job
  config.vm.network "forwarded_port", host: 4042, guest: 4042 # Spark job
  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 1024
      vb.gui = false
      vb.name = "spark"
  end
end
